msvc: add workaround for MSVC compiler bug
Mark task_promise_impl<T>::final_awaitable::return_value() method as noinline.

This fixes compilation of following tests under
x64 Release, RelWithDebInfo builds under MSVC 19.29.30137.0

tst_task.cpp(98) : error C4737:
    Unable to perform required tail call. Performance may be degraded.
tst_task.cpp(72) : error C4737:
    Unable to perform required tail call. Performance may be degraded.
tst_task.cpp(111) : error C4737:
    Unable to perform required tail call. Performance may be degraded.

tst_when_all.cpp(116) : error C4737:
    Unable to perform required tail call. Performance may be degraded.
tst_when_all.cpp(134) : error C4737:
    Unable to perform required tail call. Performance may be degraded.
tst_when_all.cpp(134) : error C4737:
    Unable to perform required tail call. Performance may be degraded.